services:
  mysql:
    image: mysql:8.0
    container_name: phantom-mask-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: phantom_mask
      MYSQL_USER: test
      MYSQL_PASSWORD: Test@123456
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
    container_name: phantom-mask-api
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5000:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=phantom_mask;User=test;Password=Test@123456;"
